name: Deploy to Azure Web Apps

on:
  push:
    branches:
      - main # Triggers flow after merging to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Azure Login using credentials
    # - name: Azure Login
    #   uses: azure/login@v1
    #   with:
    #     creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Compose App Deployment to Azure Web App for Containers (Compose)
    - name: Build and push docker images
      run: |
        docker-compose -f docker-compose.yml build
        docker tag campus-voting-app-backend ${{ secrets.ACR_LOGIN_SERVER }}/voting-backend:${{ github.sha }}
        docker tag campus-voting-app-frontend ${{ secrets.ACR_LOGIN_SERVER }}/voting-frontend:${{ github.sha }}
        echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/voting-backend:${{ github.sha }}
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/voting-frontend:${{ github.sha }}

    - name: Deploy to Azure Web App via Compose
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'campusvotingappsea7768' 
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        configuration-file: docker-compose.yml 
